services:
  - type: web
    name: django-todo-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn todo_project.wsgi:application
    envVars:
      - key: DEBUG
        value: True